/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOCategoria;
import Dao.DAOMaquinaria;
import Pojos.Categoria;
import Pojos.Maquinaria;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JDFBuscarMaquinaria extends javax.swing.JDialog {

    /**
     * Creates new form JDFBuscarMaquinaria
     */
    List<Maquinaria> listmaquinaria;
    DAOMaquinaria daomaquinaria = new DAOMaquinaria();
    JIFContrato contrato;
    JDFEditarContrato jifeditar;
    String form =null;
  
    Maquinaria maquina = new Maquinaria();
    JIFNuevaCotizacion jifnuevacot;   
    List<Categoria> listcategoriabusc = new ArrayList<>();
    DAOCategoria daocategoria = new DAOCategoria();
     Categoria categoriab = new Categoria();
    public JDFBuscarMaquinaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        listmaquinaria = daomaquinaria.view(jtabla);
    }
    public JDFBuscarMaquinaria(java.awt.Frame parent, boolean modal,JIFContrato contrato) {
        super(parent, modal);
        initComponents();
        listmaquinaria = daomaquinaria.view(jtabla,"ACTIVO","EMPRESA");
        this.contrato= contrato;
        this.setLocationRelativeTo(null);
        form="CONTRATO";
        listcategoriabusc= daocategoria.jcombobox(jcbbuscarcate, "ARRIENDO","BUSCAR");
    }
    public JDFBuscarMaquinaria(java.awt.Frame parent, boolean modal,JDFEditarContrato jifeditar) {
        super(parent, modal);
        initComponents();
        listmaquinaria = daomaquinaria.view(jtabla,"ACTIVO","EMPRESA");
        this.jifeditar=jifeditar;
        this.setLocationRelativeTo(null);
        form="EDITAR";
          listcategoriabusc= daocategoria.jcombobox(jcbbuscarcate, "ARRIENDO","BUSCAR");
    }
    public JDFBuscarMaquinaria(java.awt.Frame parent, boolean modal,JIFNuevaCotizacion jifnuevacot) {
        super(parent, modal);
        initComponents();
        listmaquinaria = daomaquinaria.view(jtabla,"ACTIVO","EMPRESA");
       this.jifnuevacot=jifnuevacot;
        this.setLocationRelativeTo(null);
        form="COTIZACION";
          listcategoriabusc= daocategoria.jcombobox(jcbbuscarcate, "ARRIENDO","BUSCAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfbbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jbtnaceptar = new javax.swing.JButton();
        jcbbuscarcate = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BUSCAR INVENTARIO ARRIENDO MAQ.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Maquina / Serie:");

        jtfbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbbuscarActionPerformed(evt);
            }
        });
        jtfbbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbbuscarKeyReleased(evt);
            }
        });

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jbtnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/accept2.png"))); // NOI18N
        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.setEnabled(false);
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });

        jcbbuscarcate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbuscarcate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbuscarcateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jcbbuscarcate, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnaceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnaceptar)
                    .addComponent(jcbbuscarcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        if(form.equals("CONTRATO")){
              int index=jtabla.getSelectedRow() ;
            if(index>=0){
            contrato.setllenarmaquinaria(listmaquinaria.get(index));
            this.dispose();
            }
        
        }
       if(form.equals("EDITAR")){
           int index=jtabla.getSelectedRow() ;
            if(index>=0){
            jifeditar.setinsertar(listmaquinaria.get(index));
            this.dispose();
            }
       
       
       }
        if(form.equals("COTIZACION")){
            maquina= listmaquinaria.get(jtabla.getSelectedRow());
          JDFCotizacionCantDias cantdia= new JDFCotizacionCantDias(new Frame(), isVisible(),maquina,jifnuevacot);
          cantdia.setVisible(true);
          this.dispose();
       
       
       }
      
      
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfbbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbbuscarKeyReleased
        // TODO add your handling code here:
        categoriab=listcategoriabusc.get(jcbbuscarcate.getSelectedIndex());
        if(jcbbuscarcate.getSelectedIndex()!=0)
        listmaquinaria=daomaquinaria.searchsentitive(jtabla,"TODO","EMPRESA", categoriab.getId(),jtfbbuscar.getText().toUpperCase());
        else
        listmaquinaria=daomaquinaria.searchsentitive(jtabla,"TODOSINCATEGORIA","EMPRESA", categoriab.getId(),jtfbbuscar.getText().toUpperCase());
        
        if(jtabla.getSelectedRow()>=0){
        jbtnaceptar.setEnabled(true);
        }else {
        jbtnaceptar.setEnabled(false);
        }
        
    }//GEN-LAST:event_jtfbbuscarKeyReleased

    private void jcbbuscarcateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbuscarcateActionPerformed
        // TODO add your handling code here:
          if(listcategoriabusc.size()>0){
             categoriab=listcategoriabusc.get(jcbbuscarcate.getSelectedIndex());
              if(jcbbuscarcate.getSelectedIndex()!=0)
            listmaquinaria=daomaquinaria.searchsentitive(jtabla,"TODO","EMPRESA", categoriab.getId(),jtfbbuscar.getText().toUpperCase());
            else
            listmaquinaria=daomaquinaria.searchsentitive(jtabla,"TODOSINCATEGORIA","EMPRESA", categoriab.getId(),jtfbbuscar.getText().toUpperCase());
         
         
         }
        if(jtabla.getSelectedRow()>=0){
        jbtnaceptar.setEnabled(true);
        }else {
        jbtnaceptar.setEnabled(false);
        }
    }//GEN-LAST:event_jcbbuscarcateActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
         if(jtabla.getSelectedRow()>=0){
        jbtnaceptar.setEnabled(true);
        }else {
        jbtnaceptar.setEnabled(false);
        }
    }//GEN-LAST:event_jtablaMouseReleased

    private void jtfbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbbuscarActionPerformed
        // TODO add your handling code here:
        jbtnaceptar.doClick();
    }//GEN-LAST:event_jtfbbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFBuscarMaquinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFBuscarMaquinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFBuscarMaquinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFBuscarMaquinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFBuscarMaquinaria dialog = new JDFBuscarMaquinaria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JComboBox jcbbuscarcate;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfbbuscar;
    // End of variables declaration//GEN-END:variables
}
