/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOReparacion;
import Pojos.Maquinaria;
import Pojos.Reparacion;

/**
 *
 * @author info2017
 */
public class JDFEnviarReparacion extends javax.swing.JDialog {

    /**
     * Creates new form JIFEnviarReparacion
     */
    DAOReparacion daoreparacion = new DAOReparacion();
    Maquinaria maq;
    Reparacion reparacion = new Reparacion();
    JIFMaquinaria jifmaq ;
    String tipoop;
    JIFReparacion jirepa;
    public JDFEnviarReparacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JDFEnviarReparacion(java.awt.Frame parent, boolean modal,Maquinaria maq,JIFMaquinaria jifmaq) {
        super(parent, modal);
        initComponents();
        jlblmaquina.setText(maq.getMaquina()+" "+maq.getMarca()+" "+maq.getSerie());
        this.maq = maq;
        this.jifmaq=jifmaq;
        jbtnaceptar.setEnabled(false);
        tipoop="REPARACION";
        this.setLocationRelativeTo(null);
    }
    public JDFEnviarReparacion(java.awt.Frame parent, boolean modal,Maquinaria maq,JIFReparacion jirepa) {
        super(parent, modal);
        initComponents();
        jlblmaquina.setText(maq.getMaquina()+" "+maq.getMarca()+" "+maq.getSerie());
        this.maq = maq;
        this.jirepa= jirepa;
       tipoop="ACTIVO";
        jbtnaceptar.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfadescripcion = new javax.swing.JTextArea();
        jbtnaceptar = new javax.swing.JButton();
        jlblmaquina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Motivo / Descripcion:");

        jtfadescripcion.setColumns(20);
        jtfadescripcion.setRows(5);
        jtfadescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfadescripcionKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtfadescripcion);

        jbtnaceptar.setText("Aceptar");
        jbtnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaceptarActionPerformed(evt);
            }
        });

        jlblmaquina.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnaceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlblmaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jlblmaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnaceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaceptarActionPerformed
        // TODO add your handling code here:
        reparacion.setIdmaqui(maq.getId());
        reparacion.setDescripci(jtfadescripcion.getText().toUpperCase());
        daoreparacion.insert(reparacion,tipoop);
        if(tipoop.equals("ACTIVO")){
            jirepa.setllenarmaq();
        }else {
            jifmaq.setvermaquina();
        }
        
        this.dispose();
        
    }//GEN-LAST:event_jbtnaceptarActionPerformed

    private void jtfadescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfadescripcionKeyReleased
        // TODO add your handling code here:
        if(jtfadescripcion.getText().replaceAll("\\s", "").length() > 0){
            jbtnaceptar.setEnabled(true);
        
        }else {
            jbtnaceptar.setEnabled(false);
        
        }
    }//GEN-LAST:event_jtfadescripcionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFEnviarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFEnviarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFEnviarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFEnviarReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFEnviarReparacion dialog = new JDFEnviarReparacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnaceptar;
    private javax.swing.JLabel jlblmaquina;
    private javax.swing.JTextArea jtfadescripcion;
    // End of variables declaration//GEN-END:variables
}
