/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAODetContrato;
import Dao.DAODetGuia;
import Dao.DAOGuia;
import Pojos.Contrato;
import Pojos.DetalleContrato;
import Pojos.Maquinaria;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JDFEditarContrato extends javax.swing.JDialog {

    /**
     * Creates new form JDFEditarContrato
     */
    Contrato contrato;
    List<DetalleContrato> listdetcontrato= new ArrayList<>();
    DAODetContrato daodetcontrato= new DAODetContrato();
    DAODetGuia daodetguia = new DAODetGuia();
    DAOGuia daoguia = new DAOGuia();     
     DetalleContrato detcontrato;
     long idguia=0;
    public JDFEditarContrato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     public JDFEditarContrato(java.awt.Frame parent, boolean modal,Contrato contrato) {
        super(parent, modal);
        initComponents();
        this.contrato=contrato;
        listdetcontrato=daodetcontrato.search(jtabla,contrato.getId());
       this.setLocationRelativeTo(null);
    }
     
    public void setinsertar(Maquinaria maq){
        List<Maquinaria> listmaquinaria = new ArrayList<>();
        listmaquinaria.add(maq);
        daodetcontrato.insert(listmaquinaria,contrato.getId());
        if(idguia==0){
            idguia=daoguia.insert(contrato, "DESPACHO");
            
        }
        jbtnimprimir.setEnabled(true);
        daodetguia.insert(listmaquinaria, idguia, true);    
        listdetcontrato=daodetcontrato.search(jtabla,contrato.getId());
    }
    
    
    
     public void validagenerar(){
        int cont=0;
        for(DetalleContrato det: listdetcontrato){
            if(det.isEntregado()==true){
            cont++;
            }
    }
        if(cont>0){
            jbtnevolver.setEnabled(true);
        }else {
            jbtnevolver.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jbtnmaquina = new javax.swing.JButton();
        jbtnevolver = new javax.swing.JButton();
        jbtnimprimir = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EDITAR CONTRATO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabla.setToolTipText("Doble clic para retirar maquina");
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jbtnmaquina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/maquina.png"))); // NOI18N
        jbtnmaquina.setText("Maquinaria");
        jbtnmaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmaquinaActionPerformed(evt);
            }
        });

        jbtnevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        jbtnevolver.setText("Devolver");
        jbtnevolver.setEnabled(false);
        jbtnevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnevolverActionPerformed(evt);
            }
        });

        jbtnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print2.png"))); // NOI18N
        jbtnimprimir.setText("Imprimir guia despacho");
        jbtnimprimir.setEnabled(false);
        jbtnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnimprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnevolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnmaquina)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnmaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnevolver)
                    .addComponent(jbtnimprimir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
          int index = jtabla.getSelectedRow();
        boolean devolver = Boolean.parseBoolean(jtabla.getValueAt(index, 4).toString());
        
        detcontrato = listdetcontrato.get(jtabla.getSelectedRow());
        detcontrato.setEntregado(devolver);
        listdetcontrato.set(index, detcontrato);
        validagenerar();
        
    }//GEN-LAST:event_jtablaMouseReleased

    private void jbtnmaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmaquinaActionPerformed
        // TODO add your handling code here:
        JDFBuscarMaquinaria buscarmaq = new JDFBuscarMaquinaria(new Frame(), isVisible(),this);
        buscarmaq.setVisible(true);
    }//GEN-LAST:event_jbtnmaquinaActionPerformed

    private void jbtnevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnevolverActionPerformed
        // TODO add your handling code here:
        long id=daoguia.insert(contrato, "DEVOLUCION");      
         System.out.println("idguia"+id);
        daodetguia.update(listdetcontrato,id,true);
        listdetcontrato = daodetcontrato.search(jtabla, contrato.getId());
        daoguia.print(id);
        jbtnevolver.setEnabled(false);
    }//GEN-LAST:event_jbtnevolverActionPerformed

    private void jbtnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirActionPerformed
        // TODO add your handling code here:
        daoguia.print(idguia);
    }//GEN-LAST:event_jbtnimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFEditarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFEditarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFEditarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFEditarContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFEditarContrato dialog = new JDFEditarContrato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnevolver;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JButton jbtnmaquina;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
}
