/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOContrato;
import Dao.DAODetCaja;
import Dao.DAODetGuia;
import Dao.DAOGuia;
import Pojos.Contrato;
import Pojos.DetalleCaja;
import Pojos.DetalleContrato;
import java.sql.Timestamp;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JDFPagarDevolucion extends javax.swing.JDialog {

    /**
     * Creates new form JDFPagarDevolucion
     */
    Double total=0.0;
    DAOContrato daocontrato = new DAOContrato();
    List<DetalleContrato> listdetc;
    DAODetGuia daodetguia = new DAODetGuia();
    DAOGuia daoguia = new DAOGuia();
    Contrato contrato;
    Timestamp fecha;
    DAODetCaja daodetcaja = new DAODetCaja();
    DetalleCaja detallecaja = new DetalleCaja();
    JIFRecojo jifecojo;
    public JDFPagarDevolucion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
     public JDFPagarDevolucion(java.awt.Frame parent, boolean modal, List<DetalleContrato> listdet,Contrato contrato,Timestamp fecha
     ,JIFRecojo jifrecojo) {
        super(parent, modal);
        initComponents();
        listdetc=daocontrato.viewpay(listdet, jtabla,jtftotal);
        total= Double.parseDouble(jtftotal.getValue().toString());
        jtftotal.setValue(total);
        this.setLocationRelativeTo(null);
        this.contrato=contrato;
        this.fecha=fecha;
        this.jifecojo=jifrecojo; 
        jtfabono.requestFocus();
    }
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jbtngenerarguia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfabono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlblmensaje = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaobservacion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jtftotal = new javax.swing.JFormattedTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtngenerarguia.setText("Generar Guia Devolución");
        jbtngenerarguia.setEnabled(false);
        jbtngenerarguia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngenerarguiaActionPerformed(evt);
            }
        });

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtabla);

        jLabel2.setText("Devolución de Maquinaria:");

        jLabel3.setText("Total:");

        jtfabono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfabonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfabonoKeyTyped(evt);
            }
        });

        jLabel6.setText("Abono:");

        jtaobservacion.setColumns(20);
        jtaobservacion.setRows(5);
        jScrollPane2.setViewportView(jtaobservacion);

        jLabel1.setText("Observacion:");

        jtftotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtftotal.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jtftotal.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfabono, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                    .addComponent(jtftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jbtngenerarguia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfabono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jbtngenerarguia)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfabonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfabonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) ||
        (c == evt.VK_BACK_SPACE) ||
        (c == evt.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
        }  
    }//GEN-LAST:event_jtfabonoKeyTyped

    private void jtfabonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfabonoKeyReleased
        // TODO add your handling code here:
        try {
            Double abono=Double.parseDouble(jtfabono.getText());
           
        
            if(abono <= total && abono>=0){
           
            jlblmensaje.setText("");
            jbtngenerarguia.setEnabled(true);
            }else {
            jlblmensaje.setText("Ingrese un monto valido");
            jbtngenerarguia.setEnabled(false);
            }
            
        } catch (Exception e) {
             jlblmensaje.setText("Ingrese un monto valido");
             jbtngenerarguia.setEnabled(false);
        }
   
    }//GEN-LAST:event_jtfabonoKeyReleased

    private void jbtngenerarguiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngenerarguiaActionPerformed
        // TODO add your handling code here:
        Double abono=Double.parseDouble(jtfabono.getText());
        contrato.setTotal(total);
        long id=daoguia.insert(contrato, "DEVOLUCION");      
        daodetguia.update(listdetc,id,false);
        detallecaja.setIdcontrato(contrato.getId());
        detallecaja.setImporte(abono);
        detallecaja.setPago(0.0);
        detallecaja.setObservacion(jtaobservacion.getText().toUpperCase());
        daodetcaja.insertpaycontrato(detallecaja);
        jifecojo.setbuscardetcontrato();
        this.dispose();
        daoguia.print(id);
    }//GEN-LAST:event_jbtngenerarguiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFPagarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFPagarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFPagarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFPagarDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFPagarDevolucion dialog = new JDFPagarDevolucion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtngenerarguia;
    private javax.swing.JLabel jlblmensaje;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextArea jtaobservacion;
    private javax.swing.JTextField jtfabono;
    private javax.swing.JFormattedTextField jtftotal;
    // End of variables declaration//GEN-END:variables
}
