/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Pojos.Maquinaria;
import java.awt.Frame;

/**
 *
 * @author info2017
 */
public class JDFTipoopMaquina extends javax.swing.JDialog {

    /**
     * Creates new form JDFTipoopMaquina
     */
    JIFMaquinaria jifmaq;
    Maquinaria maq;
    public JDFTipoopMaquina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public JDFTipoopMaquina(java.awt.Frame parent, boolean modal,JIFMaquinaria jifmaq, Maquinaria maq) {
        super(parent, modal);
        initComponents();
        this.jifmaq= jifmaq;
        this.maq = maq;
        jlblmaquina.setText(maq.getMaquina()+" "+maq.getModelo()+" "+maq.getSerie());
        if(!maq.getEstado().equals("ACTIVO")){
            jbtnenviarrepara.setEnabled(false);
        }else {jbtnenviarrepara.setEnabled(true);}
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnenviarrepara = new javax.swing.JButton();
        jbtnhistorialmov = new javax.swing.JButton();
        jbtnhistrepara = new javax.swing.JButton();
        jlblmaquina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Que tipo de operación desea hacer?");

        jbtnenviarrepara.setText("Enviar a Reparación");
        jbtnenviarrepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnenviarreparaActionPerformed(evt);
            }
        });

        jbtnhistorialmov.setText("Ver historial de movimientos");
        jbtnhistorialmov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhistorialmovActionPerformed(evt);
            }
        });

        jbtnhistrepara.setText("Ver historial de reparaciones");
        jbtnhistrepara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhistreparaActionPerformed(evt);
            }
        });

        jlblmaquina.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblmaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnenviarrepara)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnhistorialmov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnhistrepara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblmaquina)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnenviarrepara)
                    .addComponent(jbtnhistorialmov)
                    .addComponent(jbtnhistrepara))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnhistorialmovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhistorialmovActionPerformed
        // TODO add your handling code here:
        jifmaq.setmovimiento();
         this.dispose();
    }//GEN-LAST:event_jbtnhistorialmovActionPerformed

    private void jbtnenviarreparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnenviarreparaActionPerformed
        // TODO add your handling code here:
        JDFEnviarReparacion envrepara = new JDFEnviarReparacion(new Frame(), isVisible(),maq, jifmaq);
        envrepara.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnenviarreparaActionPerformed

    private void jbtnhistreparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhistreparaActionPerformed
        // TODO add your handling code here:
        JDFReparacionesMaquinaria repamaq= new JDFReparacionesMaquinaria(new Frame(), isVisible(),maq);
        repamaq.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jbtnhistreparaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDFTipoopMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDFTipoopMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDFTipoopMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDFTipoopMaquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDFTipoopMaquina dialog = new JDFTipoopMaquina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnenviarrepara;
    private javax.swing.JButton jbtnhistorialmov;
    private javax.swing.JButton jbtnhistrepara;
    private javax.swing.JLabel jlblmaquina;
    // End of variables declaration//GEN-END:variables
}
