/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOArido;
import Dao.DAOCategoria;
import Pojos.Arido;
import Pojos.Categoria;
import Pojos.SingletonEmpresa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JIFAridos extends javax.swing.JInternalFrame {

    DAOArido daoaridos = new DAOArido();
    List<Arido> listaridos;
      Arido arido = new Arido();
      boolean editar=false;
    
      DAOCategoria daocategoria = new DAOCategoria();
      Categoria categoria = new Categoria();
      Categoria categoriab = new Categoria();
      List<Categoria> listcategoria;
      SingletonEmpresa singletonempresa= SingletonEmpresa.getinstancia();
      List<Categoria> listcategoriabusc = new ArrayList<>();
    public JIFAridos() {
        
        initComponents();

        listaridos = daoaridos.view(jtabla);
        listcategoria = daocategoria.jcombobox(jcbcategoria, "VENTA","");
        listcategoriabusc= daocategoria.jcombobox(jcbbuscarcate, "VENTA","BUSCAR");
        bloquearjbtn(true, false, false, false, false);
        bloquearjtf(false, false, false,false,false,false);
    }
    public void bloquearjbtn(boolean nuevo,boolean editar,boolean guardar,boolean eliminar,boolean cancelar
     ){
    jbtnnew.setEnabled(nuevo);
    jbtneditar.setEnabled(editar);
    jbtnguardar.setEnabled(guardar);
    jbtneliminar.setEnabled(eliminar);
    jbtncancelar.setEnabled(cancelar);
//    jbtnsalir.setEnabled(salir);
     
    
    }
    public void bloquearjtf(boolean descrip, boolean cant,boolean und,boolean inv,boolean precio,boolean cat){
     jtfdescripcion.setEnabled(descrip);
     jtfcantidad.setEnabled(cant);
     jcbunidmed.setEnabled(und);
     jtfinvinicial.setEnabled(inv);
     jtfprecioventa.setEnabled(precio);
     jcbcategoria.setEnabled(cat);
     }
    public void limpiarjtf(){
     jtfdescripcion.setText("");
     jtfcantidad.setText("");
     jcbunidmed.setSelectedIndex(0);
     jtfinvinicial.setValue(0);
     jtfprecioventa.setValue(0);
     }
    
    public void validaguardar(){
     String descrip= jtfdescripcion.getText().replaceAll("\\s", "");
    
//      categoria=listcategoria.get(jcbcategoria.getSelectedIndex());
     if(!descrip.equals("") && listcategoria.size()>0){
         jbtnguardar.setEnabled(true);
     }else {
         jbtnguardar.setEnabled(false);
     }
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jtfdescripcion = new javax.swing.JTextField();
        jcbunidmed = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfbuscar = new javax.swing.JTextField();
        jtfcantidad = new javax.swing.JFormattedTextField();
        jbtnnew = new javax.swing.JButton();
        jbtneditar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jbtneliminar = new javax.swing.JButton();
        jbtncancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfprecioventa = new javax.swing.JFormattedTextField();
        jtfinvinicial = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtnimprimir = new javax.swing.JButton();
        jcbcategoria = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jcbbuscarcate = new javax.swing.JComboBox();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INVENTARIO VENTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtablaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jtabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jtfdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfdescripcionKeyReleased(evt);
            }
        });

        jcbunidmed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M3", "KG" }));
        jcbunidmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbunidmedActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripción:");

        jLabel3.setText("Cantidad Total:");

        jLabel4.setText("Und Medida:");

        jLabel5.setText("Descripcion:");

        jtfbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfbuscarKeyReleased(evt);
            }
        });

        jtfcantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jtfcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfcantidadKeyReleased(evt);
            }
        });

        jbtnnew.setBackground(new java.awt.Color(255, 255, 255));
        jbtnnew.setText("NUEVO");
        jbtnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnewActionPerformed(evt);
            }
        });

        jbtneditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneditar.setText("EDITAR");
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });

        jbtnguardar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnguardar.setText("GUARDAR");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });

        jbtneliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setText("ELIMINAR");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });

        jbtncancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbtncancelar.setText("CANCELAR");
        jbtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio Venta:");

        jtfprecioventa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfprecioventa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfprecioventaKeyReleased(evt);
            }
        });

        jtfinvinicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtfinvinicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfinvinicialKeyReleased(evt);
            }
        });

        jLabel7.setText("Inv. Inicial:");

        jbtnimprimir.setText("IMPRIMIR");
        jbtnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnimprimirActionPerformed(evt);
            }
        });

        jcbcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbcategoriaActionPerformed(evt);
            }
        });

        jLabel8.setText("Categoria");

        jcbbuscarcate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbbuscarcate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbuscarcateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtncancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jbtnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel8))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jcbcategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtfinvinicial, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfprecioventa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfcantidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbunidmed, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbbuscarcate, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbbuscarcate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnimprimir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbunidmed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfinvinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablaKeyReleased
        // TODO add your handling code here:
       
        arido=listaridos.get(jtabla.getSelectedRow());
        jtfdescripcion.setText(arido.getDescripcion());
        jtfcantidad.setValue(arido.getCantidad());
        jcbunidmed.setSelectedItem(arido.getUndmed());
        jtfprecioventa.setValue(arido.getPrecio());
        jtfinvinicial.setValue(arido.getInvinicial());
         jcbcategoria.setSelectedItem(arido.getCategoria());
        bloquearjbtn(true, true, false, true, false); 
    }//GEN-LAST:event_jtablaKeyReleased

    private void jtablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtablaMousePressed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
       System.out.println("getselect"+jcbbuscarcate.getSelectedIndex());
//        categoriab=listcategoriabusc.get(jcbbuscarcate.getSelectedIndex());
//        if(jcbbuscarcate.getSelectedIndex()!=0)
//        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"CONCATEGORIA",jtfbuscar.getText().toUpperCase());
//        else
//        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"SINCATEGORIA",jtfbuscar.getText().toUpperCase());
        
        
        if(jtabla.getSelectedRow()>=0){
            arido=listaridos.get(jtabla.getSelectedRow());
            jtfdescripcion.setText(arido.getDescripcion());
            jtfcantidad.setValue(arido.getCantidad());
            jcbunidmed.setSelectedItem(arido.getUndmed());
            jtfprecioventa.setValue(arido.getPrecio());
            jtfinvinicial.setValue(arido.getInvinicial());
            jcbcategoria.setSelectedItem(arido.getCategoria());
            bloquearjbtn(true, true, false, true, false); 
        }else {
            limpiarjtf();
            bloquearjbtn(true, false, false, false, false);
            bloquearjtf(false, false, false,false,false,false);
        }
      
    }//GEN-LAST:event_jtablaMouseReleased

    private void jbtnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnewActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true, false,true,true,true,true);
        bloquearjbtn(true, false, false, false, true);

        limpiarjtf();

        editar=false;
    }//GEN-LAST:event_jbtnnewActionPerformed

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true, false,true,true,true,true);

        editar=true;
        bloquearjbtn(true, false, false, false, true);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
        arido.setDescripcion(jtfdescripcion.getText().toUpperCase());
//        arido.setCantidad(Double.parseDouble(jtfcantidad.getValue().toString()));
        arido.setUndmed(jcbunidmed.getSelectedItem().toString());
        arido.setPrecio(Double.parseDouble(jtfprecioventa.getValue().toString()));
        arido.setInvinicial(Double.parseDouble(jtfinvinicial.getValue().toString()));
        categoria=listcategoria.get(jcbcategoria.getSelectedIndex());
        arido.setIdcatgoria(categoria.getId());
        if(editar==false){
            //  long id=Long.parseLong(jtabla.getValueAt(jtabla.getSelectedRow(), 0).toString());
            if(daoaridos.duplicate(0, jtfdescripcion.getText().toUpperCase(), "GUARDAR",categoria.getId())==true){
//                arido.setIdempresa(singletonemp.getId());
                daoaridos.insert(arido);

            }else {
                JOptionPane.showMessageDialog(null, "EL ARIDO "+jtfdescripcion.getText()+" YA SE ENCUENTRA REGISTRADA","SISTEMA",
                JOptionPane.INFORMATION_MESSAGE);
            }

        }    else{
            //                    usuario.setUsuario(jtfusuario.getText());
            
            if(daoaridos.duplicate(arido.getId(), jtfdescripcion.getText(), "EDITAR",categoria.getId())==true){
                daoaridos.update(arido);

            }else {
                JOptionPane.showMessageDialog(null, "LA TARIFA "+jtfdescripcion.getText()+" YA SE ENCUENTRA REGISTRADA","SISTEMA",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        }

         listaridos = daoaridos.view(jtabla);
        bloquearjbtn(true, false, false, false, false);
        bloquearjtf(false, false, false,false,false,false);
        limpiarjtf();

    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:

      
       
            if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR LA TARIFA","ELIMINAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                daoaridos.delete(arido.getId());
                listaridos = daoaridos.view(jtabla);
                limpiarjtf();
                bloquearjbtn(true, false, false, false, false);

            }

        
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelarActionPerformed
        // TODO add your handling code here:
        int index = jtabla.getSelectedRow();
        if(index>=0){
            jtablaMouseReleased(null);
        } else {
            limpiarjtf();
        }
        bloquearjbtn(true, false, false, false, false);
        bloquearjtf(false, false, false,false,false,false);

    }//GEN-LAST:event_jbtncancelarActionPerformed

    private void jbtnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnimprimirActionPerformed
        // TODO add your handling code here:
        daoaridos.print();
    }//GEN-LAST:event_jbtnimprimirActionPerformed

    private void jtfdescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfdescripcionKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfdescripcionKeyReleased

    private void jtfcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfcantidadKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfcantidadKeyReleased

    private void jcbunidmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbunidmedActionPerformed
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jcbunidmedActionPerformed

    private void jtfprecioventaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfprecioventaKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfprecioventaKeyReleased

    private void jtfinvinicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfinvinicialKeyReleased
        // TODO add your handling code here:
        validaguardar();
    }//GEN-LAST:event_jtfinvinicialKeyReleased

    private void jcbcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbcategoriaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbcategoriaActionPerformed

    private void jtfbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfbuscarKeyReleased
        // TODO add your handling code here:
         System.out.println("getselect"+jcbbuscarcate.getSelectedIndex());
        categoriab=listcategoriabusc.get(jcbbuscarcate.getSelectedIndex());
        if(jcbbuscarcate.getSelectedIndex()!=0)
        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"CONCATEGORIA",jtfbuscar.getText().toUpperCase());
        else
        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"SINCATEGORIA",jtfbuscar.getText().toUpperCase());
        
        
        if(jtabla.getSelectedRow()>=0){
            arido=listaridos.get(jtabla.getSelectedRow());
            jtfdescripcion.setText(arido.getDescripcion());
            jtfcantidad.setValue(arido.getCantidad());
            jcbunidmed.setSelectedItem(arido.getUndmed());
            jtfprecioventa.setValue(arido.getPrecio());
            jtfinvinicial.setValue(arido.getInvinicial());
            jcbcategoria.setSelectedItem(arido.getCategoria());
            bloquearjbtn(true, true, false, true, false); 
        }else {
            limpiarjtf();
            bloquearjbtn(true, false, false, false, false);
            bloquearjtf(false, false, false,false,false,false);
        }
    }//GEN-LAST:event_jtfbuscarKeyReleased

    private void jcbbuscarcateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbuscarcateActionPerformed
        // TODO add your handling code here:
         System.out.println("listcstgeb"+listcategoriabusc.size());
         if(listcategoriabusc.size()>0){
             categoriab=listcategoriabusc.get(jcbbuscarcate.getSelectedIndex());
             if(jcbbuscarcate.getSelectedIndex()!=0)
        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"CONCATEGORIA",jtfbuscar.getText().toUpperCase());
        else
        listaridos=daoaridos.searchsensitive(jtabla, categoriab.getId(),"SINCATEGORIA",jtfbuscar.getText().toUpperCase());
         
         
         }
         
        if(jtabla.getSelectedRow()>=0){
            arido=listaridos.get(jtabla.getSelectedRow());
            jtfdescripcion.setText(arido.getDescripcion());
            jtfcantidad.setValue(arido.getCantidad());
            jcbunidmed.setSelectedItem(arido.getUndmed());
            jtfprecioventa.setValue(arido.getPrecio());
            jtfinvinicial.setValue(arido.getInvinicial());
            jcbcategoria.setSelectedItem(arido.getCategoria());
            bloquearjbtn(true, true, false, true, false); 
        }else {
            limpiarjtf();
            bloquearjbtn(true, false, false, false, false);
            bloquearjtf(false, false, false,false,false,false);
        }
        
        
    }//GEN-LAST:event_jcbbuscarcateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JButton jbtnnew;
    private javax.swing.JComboBox jcbbuscarcate;
    private javax.swing.JComboBox jcbcategoria;
    private javax.swing.JComboBox jcbunidmed;
    private javax.swing.JTable jtabla;
    private javax.swing.JTextField jtfbuscar;
    private javax.swing.JFormattedTextField jtfcantidad;
    private javax.swing.JTextField jtfdescripcion;
    private javax.swing.JFormattedTextField jtfinvinicial;
    private javax.swing.JFormattedTextField jtfprecioventa;
    // End of variables declaration//GEN-END:variables
}
