/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAODetCaja;
import java.sql.Timestamp;
import java.util.Date;

/**
 *
 * @author info2017
 */
public class JIFMovimientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCajaMov
     */
    DAODetCaja daodetcaja = new DAODetCaja();
    public JIFMovimientos() {
        initComponents();
        Date fecha = new Date();
        jdpfecha.setDate(fecha);
        Timestamp time= new Timestamp(jdpfecha.getDate().getTime());
        jlbltotal.setText(daodetcaja.view(jtabla, "TODODIA", time, null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdpfecha = new org.jdesktop.swingx.JXDatePicker();
        jcbmes = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jlbltotal = new javax.swing.JLabel();
        jrbtndia = new javax.swing.JRadioButton();
        jrbtnmes = new javax.swing.JRadioButton();
        jbtnimprimir = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(817, 509));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MOVIMIENTO DEL DIA / MES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdpfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdpfechaActionPerformed(evt);
            }
        });

        jcbmes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jcbmes.setEnabled(false);
        jcbmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbmesActionPerformed(evt);
            }
        });

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtabla);

        jlbltotal.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jlbltotal.setForeground(new java.awt.Color(255, 51, 51));
        jlbltotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal.setText("* * *");

        buttonGroup1.add(jrbtndia);
        jrbtndia.setSelected(true);
        jrbtndia.setText("Dia");
        jrbtndia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtndiaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtnmes);
        jrbtnmes.setText("Mes");
        jrbtnmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtnmesActionPerformed(evt);
            }
        });

        jbtnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print2.png"))); // NOI18N
        jbtnimprimir.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jrbtndia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdpfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jrbtnmes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbmes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jbtnimprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdpfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbtndia)
                    .addComponent(jrbtnmes)
                    .addComponent(jbtnimprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbltotal)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtndiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtndiaActionPerformed
        // TODO add your handling code here:
      if(jrbtndia.isSelected()){
            jdpfecha.setEnabled(true);
            jcbmes.setEnabled(false);

        }
        Timestamp time= new Timestamp(jdpfecha.getDate().getTime());
       jlbltotal.setText(daodetcaja.view(jtabla, "TODODIA", time, null));
    }//GEN-LAST:event_jrbtndiaActionPerformed

    private void jrbtnmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtnmesActionPerformed
        // TODO add your handling code here:
         if(jrbtnmes.isSelected()){
            jcbmes.setEnabled(true);
            jdpfecha.setEnabled(false);
        }
       jlbltotal.setText(daodetcaja.view(jtabla, "TODOMES", null, jcbmes.getSelectedItem().toString()));
    }//GEN-LAST:event_jrbtnmesActionPerformed

    private void jdpfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdpfechaActionPerformed
        // TODO add your handling code here:
        Timestamp time= new Timestamp(jdpfecha.getDate().getTime());
        jlbltotal.setText(daodetcaja.view(jtabla, "TODODIA", time, null));
    }//GEN-LAST:event_jdpfechaActionPerformed

    private void jcbmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbmesActionPerformed
        // TODO add your handling code here:
          jlbltotal.setText(daodetcaja.view(jtabla, "TODOMES", null, jcbmes.getSelectedItem().toString()));
    }//GEN-LAST:event_jcbmesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnimprimir;
    private javax.swing.JComboBox jcbmes;
    private org.jdesktop.swingx.JXDatePicker jdpfecha;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JRadioButton jrbtndia;
    private javax.swing.JRadioButton jrbtnmes;
    private javax.swing.JTable jtabla;
    // End of variables declaration//GEN-END:variables
}
