/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOContrato;
import Dao.DAODetContrato;
import Dao.DAODetGuia;
import Dao.DAOGuia;
import Pojos.Contrato;
import Pojos.DetalleContrato;
import Pojos.SingletonEmpresa;
import java.util.List;

/**
 *
 * @author info2017
 */
public class JIFRecojo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFRecojo
     */
    DAOContrato daocontrato = new DAOContrato();
    DAODetContrato daodetcont = new DAODetContrato();
    SingletonEmpresa singletonempre = SingletonEmpresa.getinstancia();
    List<Contrato> listcontr;
    List<DetalleContrato> listdetcont;
    Contrato contrato;
    DetalleContrato detcontrato;
    DAODetGuia daodetguia = new DAODetGuia();
    DAOGuia daoguia = new DAOGuia();
    public JIFRecojo() {
        initComponents();
        listcontr=daocontrato.view(jtablacontrato, singletonempre.getId(),true,"TODOACTIVO");
    }
    public void setbuscardetcontrato(){
        if(jtablacontrato.getSelectedRow()>=0){
        contrato = listcontr.get(jtablacontrato.getSelectedRow());
        listdetcont = daodetcont.search(jtabladetalle, contrato.getId());
        }else {
        contrato = new Contrato();
        listdetcont = daodetcont.search(jtabladetalle, contrato.getId());
        }
    }
    public void validagenerar(){
        int cont=0;
        for(DetalleContrato det: listdetcont){
            if(det.isEntregado()==true){
            cont++;
            }
    }
        if(cont>0){
            jbtngenerarguiadev.setEnabled(true);
        }else {
            jbtngenerarguiadev.setEnabled(false);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablacontrato = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtabladetalle = new javax.swing.JTable();
        jbtngenerarguiadev = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtfcliente = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("DEVOLUCIÓN DE MAQUINARIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtablacontrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablacontrato.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtablacontrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtablacontratoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablacontratoMouseReleased(evt);
            }
        });
        jtablacontrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtablacontratoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtablacontrato);

        jtabladetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtabladetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtabladetalle.getTableHeader().setReorderingAllowed(false);
        jtabladetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtabladetalleMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtabladetalle);

        jbtngenerarguiadev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        jbtngenerarguiadev.setText("Generar guia devolución");
        jbtngenerarguiadev.setEnabled(false);
        jbtngenerarguiadev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngenerarguiadevActionPerformed(evt);
            }
        });

        jLabel3.setText("Cod. / Cliente / Epresa:");

        jtfcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfclienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtngenerarguiadev))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfcliente)))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtngenerarguiadev)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtablacontratoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablacontratoMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtablacontratoMousePressed

    private void jtablacontratoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtablacontratoKeyReleased
        // TODO add your handling code here:
      setbuscardetcontrato();
    }//GEN-LAST:event_jtablacontratoKeyReleased

    private void jtablacontratoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablacontratoMouseReleased
        // TODO add your handling code here:
      setbuscardetcontrato();
    }//GEN-LAST:event_jtablacontratoMouseReleased

    private void jtabladetalleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabladetalleMouseReleased
        // TODO add your handling code here:
        int index = jtabladetalle.getSelectedRow();
        boolean devolver = Boolean.parseBoolean(jtabladetalle.getValueAt(index, 4).toString());
        
        detcontrato = listdetcont.get(jtabladetalle.getSelectedRow());
        detcontrato.setEntregado(devolver);
        listdetcont.set(index, detcontrato);
        validagenerar();
//        daodetcont.update(listdetcont);
        
    }//GEN-LAST:event_jtabladetalleMouseReleased

    private void jbtngenerarguiadevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngenerarguiadevActionPerformed
        // TODO add your handling code here:
        
         
         long id=daoguia.insert(contrato, "DEVOLUCION");      
         System.out.println("idguia"+id);
        daodetguia.update(listdetcont,id,false);
        setbuscardetcontrato();
        listcontr=daocontrato.view(jtablacontrato, singletonempre.getId(),true,"TODOACTIVO");
        
        daoguia.print(id);
        jbtngenerarguiadev.setEnabled(false);
//        System.out.println(fecha.extraer());
//        JDFPagarDevolucion pagar = new JDFPagarDevolucion(new JFrame(), isVisible(),listdetcont,contrato,fecha.extraer(),this);
//        pagar.setVisible(true);
       
        
    }//GEN-LAST:event_jbtngenerarguiadevActionPerformed

    private void jtfclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfclienteKeyReleased
        // TODO add your handling code here:
        listcontr=daocontrato.searchsensitive(jtablacontrato, singletonempre.getId(), "TODOVIGENTE", 0
                , jtfcliente.getText().toUpperCase(),true);
         setbuscardetcontrato();
    }//GEN-LAST:event_jtfclienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtngenerarguiadev;
    private javax.swing.JTable jtablacontrato;
    private javax.swing.JTable jtabladetalle;
    private javax.swing.JTextField jtfcliente;
    // End of variables declaration//GEN-END:variables
}
