/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dao.DAOUsuario;
import Pojos.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author info2017
 */
public class JIFusuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFusuarios
     */
    boolean editar;
    Usuario usuario= new Usuario();
    DAOUsuario daousuario= new DAOUsuario();
    List<Usuario> listuser = new ArrayList<>();
    public JIFusuarios() {
        initComponents();
         bloquearjbtn(true, false,false, false, false,false);
         bloquearjtf(false,false);
         listuser=daousuario.view(jtabla);
         bloquearjck(false);
         
    }
 public void bloquearjbtn(boolean nuevo,boolean editar,boolean guardar,boolean eliminar,boolean cancelar,
    boolean ver ){
    jbtnnew.setEnabled(nuevo);
    jbtneditar.setEnabled(editar);
    jbtnguardar.setEnabled(guardar);
    jbtneliminar.setEnabled(eliminar);
    jbtncancelar.setEnabled(cancelar);
    jbtnver.setEnabled(ver);
//    jbtnsalir.setEnabled(salir);
     
    
    }
 public void bloquearjtf(boolean usuario,boolean clave){
     jtfusuario.setEnabled(usuario);
     jtfclave.setEnabled(clave);
 }
 public void bloquearjck(boolean  blo){
        jcknuevocontrato.setEnabled(blo);
        jckcontratosvig.setEnabled(blo);
        jckabonos.setEnabled(blo);
        jckdevoluciones.setEnabled(blo);
        jcknuevaventa.setEnabled(blo);
        jckinvarriendo.setEnabled(blo);
        jckinvventa.setEnabled(blo);
        jckingresos.setEnabled(blo);
        jckegresos.setEnabled(blo);
        jcknuevoegreso.setEnabled(blo);
        jckmovimientos.setEnabled(blo);
        jcknuevrepcliente.setEnabled(blo);
        jckreppropias.setEnabled(blo);
        jckrepcliente.setEnabled(blo);
        jckempresas.setEnabled(blo);
        jckempleados.setEnabled(blo);
        jckclientes.setEnabled(blo);
        jckporveedores.setEnabled(blo);
        jckcategorias.setEnabled(blo);
        jcknuevcotizacion.setEnabled(blo);
        jcknuevordencompra.setEnabled(blo);
        jckcotizaciones.setEnabled(blo);
        jckordenescompra.setEnabled(blo);
        jckusuarios.setEnabled(blo);
        jckempresas.setEnabled(blo);
        jcktodo.setEnabled(blo);
 
 
 }
 public void limpiarjtf(){
     jtfusuario.setText("");
     jtfclave.setText("");
     jtfusuario.requestFocus();
     
      jcknuevocontrato.setSelected(false);
        jckcontratosvig.setSelected(false);
        jckabonos.setSelected(false);
        jckdevoluciones.setSelected(false);
        jcknuevaventa.setSelected(false);
        jckinvarriendo.setSelected(false);
        jckinvventa.setSelected(false);
        jckingresos.setSelected(false);
        jckegresos.setSelected(false);
        jcknuevoegreso.setSelected(false);
        jckmovimientos.setSelected(false);
        jcknuevrepcliente.setSelected(false);
        jckreppropias.setSelected(false);
        jckrepcliente.setSelected(false);
        jckempresas.setSelected(false);
        jckempleados.setSelected(false);
        jckclientes.setSelected(false);
        jckporveedores.setSelected(false);
        jckcategorias.setSelected(false);
        jcknuevcotizacion.setSelected(false);
        jcknuevordencompra.setSelected(false);
        jckcotizaciones.setSelected(false);
        jckordenescompra.setSelected(false);
        jckusuarios.setSelected(false);
        jckempresas.setSelected(false);
        jcktodo.setSelected(false);
 }


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla = new javax.swing.JTable();
        jbtnnew = new javax.swing.JButton();
        jbtneditar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jbtneliminar = new javax.swing.JButton();
        jbtncancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfusuario = new javax.swing.JTextField();
        jtfclave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcknuevocontrato = new javax.swing.JCheckBox();
        jckcontratosvig = new javax.swing.JCheckBox();
        jckabonos = new javax.swing.JCheckBox();
        jckdevoluciones = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jckinvventa = new javax.swing.JCheckBox();
        jcknuevaventa = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jckinvarriendo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jckegresos = new javax.swing.JCheckBox();
        jckingresos = new javax.swing.JCheckBox();
        jcknuevoegreso = new javax.swing.JCheckBox();
        jckmovimientos = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jcknuevrepcliente = new javax.swing.JCheckBox();
        jckreppropias = new javax.swing.JCheckBox();
        jckrepcliente = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jckempresas = new javax.swing.JCheckBox();
        jckempleados = new javax.swing.JCheckBox();
        jckclientes = new javax.swing.JCheckBox();
        jckporveedores = new javax.swing.JCheckBox();
        jckcategorias = new javax.swing.JCheckBox();
        jcknuevcotizacion = new javax.swing.JCheckBox();
        jcknuevordencompra = new javax.swing.JCheckBox();
        jckcotizaciones = new javax.swing.JCheckBox();
        jckordenescompra = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jckusuarios = new javax.swing.JCheckBox();
        jcktodo = new javax.swing.JCheckBox();
        jbtnver = new javax.swing.JButton();

        setClosable(true);

        jtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtablaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla);

        jbtnnew.setBackground(new java.awt.Color(255, 255, 255));
        jbtnnew.setText("NUEVO");
        jbtnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnewActionPerformed(evt);
            }
        });

        jbtneditar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneditar.setText("EDITAR");
        jbtneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneditarActionPerformed(evt);
            }
        });

        jbtnguardar.setBackground(new java.awt.Color(255, 255, 255));
        jbtnguardar.setText("GUARDAR");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });

        jbtneliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtneliminar.setText("ELIMINAR");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });

        jbtncancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbtncancelar.setText("CANCELAR");
        jbtncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Clave:");

        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Arriendo");

        jcknuevocontrato.setText("Nuevo Contrato");

        jckcontratosvig.setText("Contratos Vig.");

        jckabonos.setText("Abonos");

        jckdevoluciones.setText("Devoluciones");

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Venta");

        jckinvventa.setText("Inv. Venta");

        jcknuevaventa.setText("Nuev. Venta");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Inventario");

        jckinvarriendo.setText("Inv. Arriendo");

        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Caja");

        jckegresos.setText("Egresos");

        jckingresos.setText("Ingresos");

        jcknuevoegreso.setText("Nuevo Egreso");

        jckmovimientos.setText("Movimientos");

        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Taller");

        jcknuevrepcliente.setText("Nuev. Rep. Cliente");

        jckreppropias.setText("Rep. Propias");

        jckrepcliente.setText("Rep. Cliente");

        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Otros");

        jckempresas.setText("Empresas");

        jckempleados.setText("Empleados");

        jckclientes.setText("Clientes");

        jckporveedores.setText("Proveedores");

        jckcategorias.setText("Categorias");

        jcknuevcotizacion.setText("Nuev. Cotizacion");

        jcknuevordencompra.setText("Nuev. Orden C.");

        jckcotizaciones.setText("Cotizaciones");

        jckordenescompra.setText("Ordenes Compra");

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Usuarios");

        jckusuarios.setText("Usuarios");

        jcktodo.setForeground(new java.awt.Color(255, 51, 51));
        jcktodo.setText("Seleccionar todo");

        jbtnver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ver.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcknuevocontrato)
                            .addComponent(jckcontratosvig)
                            .addComponent(jckabonos)
                            .addComponent(jckdevoluciones)
                            .addComponent(jLabel4)
                            .addComponent(jcknuevaventa)
                            .addComponent(jLabel5)
                            .addComponent(jckinvventa)
                            .addComponent(jckinvarriendo)
                            .addComponent(jLabel6)
                            .addComponent(jckingresos)
                            .addComponent(jckegresos)
                            .addComponent(jcknuevoegreso)
                            .addComponent(jckmovimientos))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jckordenescompra)
                            .addComponent(jckcotizaciones)
                            .addComponent(jcknuevordencompra)
                            .addComponent(jcknuevcotizacion)
                            .addComponent(jckcategorias)
                            .addComponent(jckporveedores)
                            .addComponent(jckclientes)
                            .addComponent(jckempleados)
                            .addComponent(jckempresas)
                            .addComponent(jLabel8)
                            .addComponent(jckrepcliente)
                            .addComponent(jckreppropias)
                            .addComponent(jcknuevrepcliente)
                            .addComponent(jckusuarios)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addComponent(jcktodo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(jtfclave))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnver))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jbtnver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jcktodo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcknuevocontrato)
                            .addComponent(jcknuevrepcliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckcontratosvig)
                            .addComponent(jckreppropias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckabonos)
                            .addComponent(jckrepcliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckdevoluciones)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jckempresas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcknuevaventa)
                            .addComponent(jckempleados))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jckclientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckinvventa)
                            .addComponent(jckporveedores))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckinvarriendo)
                            .addComponent(jckcategorias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcknuevcotizacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckingresos)
                            .addComponent(jcknuevordencompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jckegresos)
                            .addComponent(jckcotizaciones))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcknuevoegreso)
                            .addComponent(jckordenescompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jckmovimientos)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jckusuarios))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnewActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true,true);
        bloquearjbtn(true, false, false, false, true,false);
        bloquearjck(true);
        limpiarjtf();

        editar=false;
       
    }//GEN-LAST:event_jbtnnewActionPerformed

    private void jbtneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneditarActionPerformed
        // TODO add your handling code here:
        bloquearjtf(true,true);

        editar=true;
        bloquearjbtn(true, false, false, false, true,true);
    }//GEN-LAST:event_jbtneditarActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        // TODO add your handling code here:
     usuario.setUsuario(jtfusuario.getText());
     usuario.setClave(new String (jtfclave.getPassword()));
     usuario.setNuevocontrato(jcknuevocontrato.isSelected());
    usuario.setContratosvig(jckcontratosvig.isSelected());
    usuario.setAbonos(jckabonos.isSelected());
    usuario.setDevoluciones(jckdevoluciones.isSelected());
    usuario.setNuevaventa(jcknuevaventa.isSelected());
    usuario.setInvarriendo(jckinvarriendo.isSelected());
    usuario.setInvventa(jckinvventa.isSelected());
    usuario.setIngreso(jckingresos.isSelected());
    usuario.setEgreso(jckegresos.isSelected());
    usuario.setNuevoegreso(jcknuevoegreso.isSelected());
    usuario.setMovimientos(jckmovimientos.isSelected());
    usuario.setNuevarepcliente(jcknuevrepcliente.isSelected());
    usuario.setReparacionpropia(jckreppropias.isSelected());
    usuario.setReparacioncliente(jckrepcliente.isSelected());
    usuario.setEmpresas(jckempresas.isSelected());
    usuario.setEmpleados(jckempleados.isSelected());
    usuario.setCliente(jckclientes.isSelected());
    usuario.setProveedores(jckporveedores.isSelected());
    usuario.setCategorias(jckcategorias.isSelected());
    usuario.setNuevacotizacion(jcknuevcotizacion.isSelected());
    usuario.setNuevaordencompra(jcknuevordencompra.isSelected());
    usuario.setCotizaciones(jckcotizaciones.isSelected());
    usuario.setOrdencompra(jckordenescompra.isSelected());
    usuario.setUsuariobo(jckusuarios.isSelected());
    usuario.setMiempresa(jckempresas.isSelected());

        if(editar==false){
            //  long id=Long.parseLong(jtabla.getValueAt(jtabla.getSelectedRow(), 0).toString());
            if(daousuario.duplicate(0, jtfusuario.getText(), "GUARDAR")==true){

                daousuario.insert(usuario);

            }else {
                JOptionPane.showMessageDialog(null, " El usuario "+jtfusuario.getText()+" ya se encuentra en uso","SISTEMA",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        }    else{
            //                    usuario.setUsuario(jtfusuario.getText());

            if(daousuario.duplicate(usuario.getId(),jtfusuario.getText(), "EDITAR")==true){
                daousuario.update(usuario);

            }else {
                JOptionPane.showMessageDialog(null, " El usuario "+jtfusuario.getText()+" ya se encuentra en uso","SISTEMA",
                    JOptionPane.INFORMATION_MESSAGE);
            }

        }

        listuser = daousuario.view(jtabla);
        bloquearjbtn(true, false, false, false, false,false);
        bloquearjtf(true,true);
        bloquearjck(true);
        
        limpiarjtf();
    }//GEN-LAST:event_jbtnguardarActionPerformed

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar al usuario","ELIMINAR",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            daousuario.delete(usuario.getId());
            listuser = daousuario.view(jtabla);
            limpiarjtf();
            bloquearjbtn(true, false, false, false, false,false);

        }
    }//GEN-LAST:event_jbtneliminarActionPerformed

    private void jbtncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncancelarActionPerformed
        // TODO add your handling code here:
        int index = jtabla.getSelectedRow();
        if(index>=0){
            jtablaMouseReleased(null);
        } else {
            limpiarjtf();
        }
        bloquearjbtn(true, false, false, false, false,false);
        bloquearjtf(false,false);
    }//GEN-LAST:event_jbtncancelarActionPerformed

    private void jtablaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaMouseReleased
        // TODO add your handling code here:
        usuario= listuser.get(jtabla.getSelectedRow());
        
        jtfusuario.setText(usuario.getUsuario());
        jtfclave.setText(usuario.getClave());
        jcknuevocontrato.setSelected(usuario.isNuevocontrato());
        jckcontratosvig.setSelected(usuario.isContratosvig());
        jckabonos.setSelected(usuario.isAbonos());
        jckdevoluciones.setSelected(usuario.isDevoluciones());
        jcknuevaventa.setSelected(usuario.isNuevaventa());
        jckinvarriendo.setSelected(usuario.isInvarriendo());
        jckinvventa.setSelected(usuario.isInvventa());
        jckingresos.setSelected(usuario.isIngreso());
        jckegresos.setSelected(usuario.isEgreso());
        jcknuevoegreso.setSelected(usuario.isNuevoegreso());
        jckmovimientos.setSelected(usuario.isMovimientos());
        jcknuevrepcliente.setSelected(usuario.isNuevarepcliente());
        jckreppropias.setSelected(usuario.isReparacionpropia());
        jckrepcliente.setSelected(usuario.isReparacioncliente());
        jckempresas.setSelected(usuario.isEmpresas());
        jckempleados.setSelected(usuario.isEmpleados());
        jckclientes.setSelected(usuario.isCliente());
        jckporveedores.setSelected(usuario.isProveedores());
        jckcategorias.setSelected(usuario.isCategorias());
        jcknuevcotizacion.setSelected(usuario.isNuevacotizacion());
        jcknuevordencompra.setSelected(usuario.isNuevaordencompra());
        jckcotizaciones.setSelected(usuario.isCotizaciones());
        jckordenescompra.setSelected(usuario.isOrdencompra());
        jckusuarios.setSelected(usuario.isUsuariobo());
        jckempresas.setSelected(usuario.isEmpresas());

    }//GEN-LAST:event_jtablaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtncancelar;
    private javax.swing.JButton jbtneditar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnnew;
    private javax.swing.JButton jbtnver;
    private javax.swing.JCheckBox jckabonos;
    private javax.swing.JCheckBox jckcategorias;
    private javax.swing.JCheckBox jckclientes;
    private javax.swing.JCheckBox jckcontratosvig;
    private javax.swing.JCheckBox jckcotizaciones;
    private javax.swing.JCheckBox jckdevoluciones;
    private javax.swing.JCheckBox jckegresos;
    private javax.swing.JCheckBox jckempleados;
    private javax.swing.JCheckBox jckempresas;
    private javax.swing.JCheckBox jckingresos;
    private javax.swing.JCheckBox jckinvarriendo;
    private javax.swing.JCheckBox jckinvventa;
    private javax.swing.JCheckBox jckmovimientos;
    private javax.swing.JCheckBox jcknuevaventa;
    private javax.swing.JCheckBox jcknuevcotizacion;
    private javax.swing.JCheckBox jcknuevocontrato;
    private javax.swing.JCheckBox jcknuevoegreso;
    private javax.swing.JCheckBox jcknuevordencompra;
    private javax.swing.JCheckBox jcknuevrepcliente;
    private javax.swing.JCheckBox jckordenescompra;
    private javax.swing.JCheckBox jckporveedores;
    private javax.swing.JCheckBox jckrepcliente;
    private javax.swing.JCheckBox jckreppropias;
    private javax.swing.JCheckBox jcktodo;
    private javax.swing.JCheckBox jckusuarios;
    private javax.swing.JTable jtabla;
    private javax.swing.JPasswordField jtfclave;
    private javax.swing.JTextField jtfusuario;
    // End of variables declaration//GEN-END:variables
}
